import { Inter_Tight } from "next/font/google";
import "./globals.css";
import LenisSmoothScroll from "@/components/SmoothScroll/Lenis";

const interTight = Inter_Tight({
  variable: "--font-inter-tight",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${interTight.variable} antialiased`}
      >
        <LenisSmoothScroll />
        {children}
      </body>
    </html>
  );
}
